name: Java to GCP Workflow

on:
  push:

jobs:
  Java-Workflow:
    uses: DevOpsORT-proyecto/obligatorioDevOps-infra/.github/workflows/Java-Workflow.yml@main
    with:
      service-name: Payments
      sonar-project-key: DevOpsORT-proyecto_payments-service
    secrets: inherit